import { Product } from '../types/product';

export const getMockProducts = (): Product[] => [
  {
    id: '1',
    name: 'ドスパラ G-Tune 2024モデル',
    maker: 'ドスパラ',
    price: 150000,
    effectiveprice: 140000,
    cpu: 'Core i7-14700K',
    gpu: 'RTX 4070 (12GB)',
    memory: '32GB',
    storage: '1TB',
    imageUrl: 'https://picsum.photos/300/200?random=1',
    productUrl: 'https://example.com/product1',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 10000 }],
    discountrate: 7,
    shippingFee: 0,
    category: 'ゲーミングPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '2',
    name: 'パソコン工房 ゲーミングPC',
    maker: 'パソコン工房',
    price: 120000,
    effectiveprice: 110000,
    cpu: 'Core i5-14600K',
    gpu: 'RTX 4060 (8GB)',
    memory: '16GB',
    storage: '512GB',
    imageUrl: 'https://picsum.photos/300/200?random=2',
    productUrl: 'https://example.com/product2',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 8000 }],
    discountrate: 8,
    shippingFee: 0,
    category: 'ゲーミングPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '3',
    name: 'ツクモ カスタムPC',
    maker: 'ツクモ',
    price: 180000,
    effectiveprice: 170000,
    cpu: 'Core i9-14900K',
    gpu: 'RTX 4080 (16GB)',
    memory: '64GB',
    storage: '2TB',
    imageUrl: 'https://picsum.photos/300/200?random=3',
    productUrl: 'https://example.com/product3',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 15000 }],
    discountrate: 6,
    shippingFee: 0,
    category: 'ハイエンドPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '4',
    name: 'サイコム クリエイターPC',
    maker: 'サイコム',
    price: 200000,
    effectiveprice: 190000,
    cpu: 'Core Ultra 9 185H',
    gpu: 'RTX 4090 (24GB)',
    memory: '64GB',
    storage: '2TB',
    imageUrl: 'https://picsum.photos/300/200?random=4',
    productUrl: 'https://example.com/product4',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 20000 }],
    discountrate: 5,
    shippingFee: 0,
    category: 'クリエイターPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '5',
    name: 'レノボ ThinkPad',
    maker: 'レノボ',
    price: 100000,
    effectiveprice: 95000,
    cpu: 'Core i5-13500H',
    gpu: 'Intel Iris Xe Graphics',
    memory: '16GB',
    storage: '512GB',
    imageUrl: 'https://picsum.photos/300/200?random=5',
    productUrl: 'https://example.com/product5',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 5000 }],
    discountrate: 5,
    shippingFee: 0,
    category: 'ビジネスPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '6',
    name: 'フロンティア エントリーPC',
    maker: 'フロンティア',
    price: 80000,
    effectiveprice: 75000,
    cpu: 'Core i3-14100',
    gpu: 'GTX 1650 (4GB)',
    memory: '8GB',
    storage: '256GB',
    imageUrl: 'https://picsum.photos/300/200?random=6',
    productUrl: 'https://example.com/product6',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 3000 }],
    discountrate: 6,
    shippingFee: 0,
    category: 'エントリーPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '7',
    name: 'ドスパラ AMD Ryzen PC',
    maker: 'ドスパラ',
    price: 130000,
    effectiveprice: 120000,
    cpu: 'Ryzen 7 7800X3D',
    gpu: 'RX 7800 XT (16GB)',
    memory: '32GB',
    storage: '1TB',
    imageUrl: 'https://picsum.photos/300/200?random=7',
    productUrl: 'https://example.com/product7',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 10000 }],
    discountrate: 8,
    shippingFee: 0,
    category: 'ゲーミングPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '8',
    name: 'パソコン工房 ハイエンド',
    maker: 'パソコン工房',
    price: 250000,
    effectiveprice: 240000,
    cpu: 'Core i9-14900KS',
    gpu: 'RTX 4090 (24GB)',
    memory: '64GB',
    storage: '2TB',
    imageUrl: 'https://picsum.photos/300/200?random=8',
    productUrl: 'https://example.com/product8',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 25000 }],
    discountrate: 4,
    shippingFee: 0,
    category: 'ハイエンドPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '9',
    name: 'ツクモ ミニPC',
    maker: 'ツクモ',
    price: 90000,
    effectiveprice: 85000,
    cpu: 'Core i5-13400',
    gpu: 'Intel UHD Graphics 730',
    memory: '16GB',
    storage: '512GB',
    imageUrl: 'https://picsum.photos/300/200?random=9',
    productUrl: 'https://example.com/product9',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 5000 }],
    discountrate: 6,
    shippingFee: 0,
    category: 'ミニPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '10',
    name: 'サイコム ワークステーション',
    maker: 'サイコム',
    price: 300000,
    effectiveprice: 290000,
    cpu: 'Core Ultra 9 185H',
    gpu: 'RTX 5000 Ada (32GB)',
    memory: '128GB',
    storage: '4TB',
    imageUrl: 'https://picsum.photos/300/200?random=10',
    productUrl: 'https://example.com/product10',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 30000 }],
    discountrate: 3,
    shippingFee: 0,
    category: 'ワークステーション',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '11',
    name: 'レノボ Legion',
    maker: 'レノボ',
    price: 160000,
    effectiveprice: 150000,
    cpu: 'Core i7-13700H',
    gpu: 'RTX 4070 (8GB)',
    memory: '32GB',
    storage: '1TB',
    imageUrl: 'https://picsum.photos/300/200?random=11',
    productUrl: 'https://example.com/product11',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 12000 }],
    discountrate: 6,
    shippingFee: 0,
    category: 'ゲーミングノート',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '12',
    name: 'フロンティア クリエイター',
    maker: 'フロンティア',
    price: 140000,
    effectiveprice: 130000,
    cpu: 'Core i7-14700',
    gpu: 'RTX 4060 Ti (8GB)',
    memory: '32GB',
    storage: '1TB',
    imageUrl: 'https://picsum.photos/300/200?random=12',
    productUrl: 'https://example.com/product12',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 10000 }],
    discountrate: 7,
    shippingFee: 0,
    category: 'クリエイターPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '13',
    name: 'ドスパラ エントリー',
    maker: 'ドスパラ',
    price: 70000,
    effectiveprice: 65000,
    cpu: 'Core i3-13100',
    gpu: 'GTX 1660 Super (6GB)',
    memory: '8GB',
    storage: '256GB',
    imageUrl: 'https://picsum.photos/300/200?random=13',
    productUrl: 'https://example.com/product13',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 3000 }],
    discountrate: 7,
    shippingFee: 0,
    category: 'エントリーPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '14',
    name: 'パソコン工房 AMD',
    maker: 'パソコン工房',
    price: 110000,
    effectiveprice: 100000,
    cpu: 'Ryzen 5 7600X',
    gpu: 'RX 7600 (8GB)',
    memory: '16GB',
    storage: '512GB',
    imageUrl: 'https://picsum.photos/300/200?random=14',
    productUrl: 'https://example.com/product14',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 8000 }],
    discountrate: 9,
    shippingFee: 0,
    category: 'ゲーミングPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '15',
    name: 'ツクモ ハイエンド',
    maker: 'ツクモ',
    price: 220000,
    effectiveprice: 210000,
    cpu: 'Core i9-14900K',
    gpu: 'RTX 4080 Super (16GB)',
    memory: '64GB',
    storage: '2TB',
    imageUrl: 'https://picsum.photos/300/200?random=15',
    productUrl: 'https://example.com/product15',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 20000 }],
    discountrate: 5,
    shippingFee: 0,
    category: 'ハイエンドPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '16',
    name: 'サイコム ミニ',
    maker: 'サイコム',
    price: 85000,
    effectiveprice: 80000,
    cpu: 'Core i5-13400F',
    gpu: 'GTX 1660 Ti (6GB)',
    memory: '16GB',
    storage: '512GB',
    imageUrl: 'https://picsum.photos/300/200?random=16',
    productUrl: 'https://example.com/product16',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 5000 }],
    discountrate: 6,
    shippingFee: 0,
    category: 'ミニPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '17',
    name: 'レノボ IdeaPad',
    maker: 'レノボ',
    price: 95000,
    effectiveprice: 90000,
    cpu: 'Core i5-1335U',
    gpu: 'Intel Iris Xe Graphics',
    memory: '16GB',
    storage: '512GB',
    imageUrl: 'https://picsum.photos/300/200?random=17',
    productUrl: 'https://example.com/product17',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 5000 }],
    discountrate: 5,
    shippingFee: 0,
    category: 'ノートPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '18',
    name: 'フロンティア ゲーミング',
    maker: 'フロンティア',
    price: 170000,
    effectiveprice: 160000,
    cpu: 'Core i7-14700KF',
    gpu: 'RTX 4070 Ti (12GB)',
    memory: '32GB',
    storage: '1TB',
    imageUrl: 'https://picsum.photos/300/200?random=18',
    productUrl: 'https://example.com/product18',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 15000 }],
    discountrate: 6,
    shippingFee: 0,
    category: 'ゲーミングPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '19',
    name: 'ドスパラ クリエイター',
    maker: 'ドスパラ',
    price: 190000,
    effectiveprice: 180000,
    cpu: 'Core i7-14700K',
    gpu: 'RTX 4070 Ti (12GB)',
    memory: '64GB',
    storage: '2TB',
    imageUrl: 'https://picsum.photos/300/200?random=19',
    productUrl: 'https://example.com/product19',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 18000 }],
    discountrate: 5,
    shippingFee: 0,
    category: 'クリエイターPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '20',
    name: 'パソコン工房 ワークステーション',
    maker: 'パソコン工房',
    price: 280000,
    effectiveprice: 270000,
    cpu: 'Core Ultra 9 185H',
    gpu: 'RTX 4000 Ada (20GB)',
    memory: '128GB',
    storage: '4TB',
    imageUrl: 'https://picsum.photos/300/200?random=20',
    productUrl: 'https://example.com/product20',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 28000 }],
    discountrate: 4,
    shippingFee: 0,
    category: 'ワークステーション',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '21',
    name: 'ツクモ エントリー',
    maker: 'ツクモ',
    price: 75000,
    effectiveprice: 70000,
    cpu: 'Core i3-13100F',
    gpu: 'GTX 1650 (4GB)',
    memory: '8GB',
    storage: '256GB',
    imageUrl: 'https://picsum.photos/300/200?random=21',
    productUrl: 'https://example.com/product21',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 4000 }],
    discountrate: 7,
    shippingFee: 0,
    category: 'エントリーPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '22',
    name: 'サイコム AMD',
    maker: 'サイコム',
    price: 120000,
    effectiveprice: 110000,
    cpu: 'Ryzen 7 7700X',
    gpu: 'RX 7700 XT (12GB)',
    memory: '32GB',
    storage: '1TB',
    imageUrl: 'https://picsum.photos/300/200?random=22',
    productUrl: 'https://example.com/product22',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 10000 }],
    discountrate: 8,
    shippingFee: 0,
    category: 'ゲーミングPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '23',
    name: 'レノボ ThinkPad X1 Carbon',
    maker: 'レノボ',
    price: 200000,
    effectiveprice: 195000,
    cpu: 'Core Ultra 7 155H',
    gpu: 'Intel Arc Graphics',
    memory: '32GB',
    storage: '1TB',
    imageUrl: 'https://picsum.photos/300/200?random=23',
    productUrl: 'https://example.com/product23',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 15000 }],
    discountrate: 3,
    shippingFee: 0,
    category: 'モバイルPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '24',
    name: 'フロンティア ハイエンドPC',
    maker: 'フロンティア',
    price: 260000,
    effectiveprice: 250000,
    cpu: 'Core i9-14900K',
    gpu: 'RTX 4080 (16GB)',
    memory: '64GB',
    storage: '2TB',
    imageUrl: 'https://picsum.photos/300/200?random=24',
    productUrl: 'https://example.com/product24',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 20000 }],
    discountrate: 4,
    shippingFee: 0,
    category: 'ハイエンドPC',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '25',
    name: 'ドスパラ G-Tune クリエイター',
    maker: 'ドスパラ',
    price: 240000,
    effectiveprice: 230000,
    cpu: 'Core i9-14900K',
    gpu: 'RTX 4080 (16GB)',
    memory: '64GB',
    storage: '2TB',
    imageUrl: 'https://picsum.photos/300/200?random=25',
    productUrl: 'https://example.com/product25',
    isActive: true,
    campaigns: [{ type: 'クーポン', amount: 18000 }],
    discountrate: 4,
    shippingFee: 0,
    category: 'クリエイターPC',
    createdAt: new Date(),
    updatedAt: new Date()
  }
];
